#!/system/bin/sh
#
# Created by Calkulin

echo 100000 > /proc/sys/kernel/sched_rt_period_us

echo 95000 > /proc/sys/kernel/sched_rt_runtime_us

# Added By Mik (credits to Juwe11 for ram scripts)

if [ -e /sys/module/lowmemorykiller/parameters/adj ]; then
	echo "0,1,2,4,6,15" > /sys/module/lowmemorykiller/parameters/adj
fi

if [ -e /sys/module/lowmemorykiller/parameters/minfree ]; then
	echo "2560,4096,5632,10240,11776,14848" > /sys/module/lowmemorykiller/parameters/minfree
fi

if [ -e /proc/sys/vm/swappiness ]; then
	echo "20" > /proc/sys/vm/swappiness
fi

if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
	echo "70" > /proc/sys/vm/vfs_cache_pressure
fi

if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
	echo "3000" > /proc/sys/vm/dirty_expire_centisecs
fi

if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
	echo "500" > /proc/sys/vm/dirty_writeback_centisecs
fi

if [ -e /proc/sys/vm/dirty_ratio ]; then
	echo "15" > /proc/sys/vm/dirty_ratio
fi

if [ -e /proc/sys/vm/dirty_background_ratio ]; then
	echo "3" > /proc/sys/vm/dirty_background_ratio
fi

if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
	echo "4096" > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

setprop dalvik.vm.execution-mode int:fast

busybox mount -o remount,noatime,noauto_da_alloc,barrier=0 /system
busybox mount -o remount,noatime,noauto_da_alloc,barrier=0 /data
busybox mount -o remount,noatime,noauto_da_alloc,barrier=0 /cache

# defrag database
for i in \
`find /data -iname "*.db"`
do \
sqlite3 $i 'VACUUM;'; 
done